Update 4-error-fstat.js
HowProgrammingWorks/Files pull request #5
Opened 2023-07-08 18:38 UTC by Haliont

- Uses more undrestandable variable names
- Uses for loop instead of forEach

2023-07-09 04:23 UTC, tshemsedinov requested changes
- Use camelCase: `fileName`
- Here is a case for .map

2023-07-09 06:25 UTC, Haliont commented
> * Here is a case for .map

But if we use map in this case, wouldn't it be semantically incorrect because there will be mutation of the external variable (stats) inside map, while map is intended for immutable behavior?

2023-07-09 14:21 UTC, tshemsedinov commented
> But if we use map in this case, wouldn't it be semantically incorrect because there will be mutation of the external variable (stats) inside map, while map is intended for immutable behavior?

You can easily do it without mutations. Reflect array of names to array of stats, we do not even need counters, `printResult`, and `isLastProcessed` here.

2023-07-13 14:54 UTC, kzemlyak commented
But for that, I will need to use Promises to do this. Can I use them in this example?

2023-07-13 15:13 UTC, tshemsedinov commented
```js
const promises = files.map((fileName) => fs.lstat(fileName));
Promise.allSettled(promises).then((stats) => {
  console.dir(stats);
});
```

2023-07-13 15:22 UTC, Haliont commented
I just thought that it's not worth using Promises in this example since they were not originally included

2023-07-13 15:44 UTC, tshemsedinov commented
We can refactor this even without promises, using closures, I'll provide multiple solutions a bit later

2023-07-13 15:44 UTC, tshemsedinov commented on JavaScript/4-error-fstat.js
>  const fs = require('node:fs');
```suggestion
const fs = require('node:fs').promises;
```

2023-07-13 15:46 UTC, merged